package no.nav.helsearbeidsgiver.domene.inntektsmelding

import kotlinx.serialization.Serializable

@Serializable
enum class NaturalytelseKode {
    AKSJERGRUNNFONDSBEVISTILUNDERKURS,
    ANNET,
    BEDRIFTSBARNEHAGEPLASS,
    BESOEKSREISERHJEMMETANNET,
    BIL,
    BOLIG,
    ELEKTRONISKKOMMUNIKASJON,
    FRITRANSPORT,
    INNBETALINGTILUTENLANDSKPENSJONSORDNING,
    KOSTBESPARELSEIHJEMMET,
    KOSTDAGER,
    KOSTDOEGN,
    LOSJI,
    OPSJONER,
    RENTEFORDELLAAN,
    SKATTEPLIKTIGDELFORSIKRINGER,
    TILSKUDDBARNEHAGEPLASS,
    YRKEBILTJENESTLIGBEHOVKILOMETER,
    YRKEBILTJENESTLIGBEHOVLISTEPRIS,
}
