name: Publish Snapshot

on:
  push:
    branches:
      - dev/**

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Get Version
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: echo "CURRENT_VERSION=$(./gradlew :printVersion)" >> $GITHUB_ENV
      - name: Publish artifact
        if: ${{ endsWith(env.CURRENT_VERSION, '-SNAPSHOT') }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
